<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Bloque 1, sistema-->
    <xs:element name="sistema">
        <xs:complexType>
            <xs:sequence>
                <!-- Bloque 2 estudiante-->
                <xs:element name="estudiante" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="matricula" type="matriculaType"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <!-- Bloque 3 materias-->
                            <xs:element name="materias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- Bloque 4 materia-->
                                        <xs:element name="materia" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:integer"/>
                                                    <xs:element name="nombre" type="nombreMateriaType"/>
                                                    <xs:element name="creditos" type="creditosType"/>
                                                    <xs:element name="calificacion" type="calificacionType" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Matrícula: S o s + año (00 a 26) + 6 dígitos -->
    <xs:simpleType name="matriculaType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[Ss](0[0-9]|1[0-9]|2[0-6])[0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nombreMateriaType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="creditosType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="25"/>
        </xs:restriction>
    </xs:simpleType>

<!-- Calificación estricta en enteros de 0 a 100 -->
<xs:simpleType name="calificacionType">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="100"/>
    </xs:restriction>
</xs:simpleType>
</xs:schema>